# Generated by Django 3.0.7 on 2020-06-11 03:44

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='answer',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
