# Generated by Django 3.0.7 on 2020-06-11 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_auto_20200610_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.Choises'),
        ),
    ]
